name: xtensor-io
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  # Host dependencies
  - openimageio >=3.0,<4
  - fmt
  - libsndfile
  - zlib
  - highfive
  - blosc
  - gdal
  - nlohmann_json
  - google-cloud-cpp >=3.0,<4
  - aws-sdk-cpp
  - xtensor=0.25.0
  - cpp-filesystem

